version: '3.8'

services:
  ssl-gcn-api:
    platform: linux/amd64  # 在 Apple Silicon 上避免相容性問題
    build:
      context: ../..
      dockerfile: microservice/docker/Dockerfile
    image: ssl-gcn-api:latest
    container_name: ssl-gcn-toxicity-prediction
    ports:
      - "8007:8007"
    environment:
      - PYTHONUNBUFFERED=1
      - API_PORT=8007
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8007/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      # 可選：掛載模型目錄以便更新模型
      - ../../model:/app/model:ro
    networks:
      - ssl-gcn-network

networks:
  ssl-gcn-network:
    driver: bridge 